-- AUTOINCREMENTOS - PATRONES Y TRIGGERS

CREATE TABLE tb_identificacion(
ID INT AUTO_INCREMENT NOT NULL,
DESCRIPCION VARCHAR(50) NULL,
PRIMARY KEY(ID)
);

INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente A');

SELECT * FROM tb_identificacion;

INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente B');
INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente C');
INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente D');
INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente E');
INSERT INTO tb_identificacion(DESCRIPCION)
VALUES ('Cliente F');

SELECT * FROM tb_identificacion;

DELETE FROM tb_identificacion WHERE ID= 6;
INSERT INTO tb_identificacion(ID, DESCRIPCION)
VALUES (100, 'Cliente G');
INSERT INTO tb_identificacion(ID, DESCRIPCION)
VALUES (NULL, 'Cliente I');

CREATE TABLE tb_default(
ID INT AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(100) NULL,
CIUDAD VARCHAR(50) DEFAULT 'Monterrey',
FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
PRIMARY KEY(ID)
);

INSERT INTO tb_default 
(DESCRIPCION, DIRECCION, CIUDAD, FECHA_CREACION)
VALUES ('Cliente X', 'Calle Sol, 525', 'Cancún', '2021-01-01');

SELECT * FROM tb_default;

INSERT INTO tb_default 
(DESCRIPCION)
VALUES ('Cliente Y');

CREATE TABLE tb_facturacion(
FECHA DATE NULL,
VENTA_TOTAL FLOAT
);

CREATE TABLE `tb_factura1` (
  `NUMERO` varchar(5) NOT NULL,
  `FECHA` date DEFAULT NULL,
  `DNI` varchar(11) NOT NULL,
  `MATRICULA` varchar(5) NOT NULL,
  `IMPUESTO` float DEFAULT NULL,
  PRIMARY KEY (`NUMERO`),
  KEY `FK_CLIENTE1` (`DNI`),
  KEY `FK_VENDEDOR1` (`MATRICULA`),
  CONSTRAINT `FK_CLIENTE1` FOREIGN KEY (`DNI`) REFERENCES `tb_cliente` (`DNI`),
  CONSTRAINT `FK_VENDEDOR1` FOREIGN KEY (`MATRICULA`) REFERENCES `tb_vendedor` (`MATRICULA`)
) ;

CREATE TABLE `tb_items_factura` (
  `NUMERO` varchar(5) NOT NULL,
  `CODIGO` varchar(10) NOT NULL,
  `CANTIDAD` int DEFAULT NULL,
  `PRECIO` float DEFAULT NULL,
  PRIMARY KEY (`NUMERO`,`CODIGO`),
  KEY `FK_PRODUCTO` (`CODIGO`),
  CONSTRAINT `FK_FACTURA2` FOREIGN KEY (`NUMERO`) REFERENCES `tb_factura1` (`NUMERO`),
  CONSTRAINT `FK_PRODUCTO2` FOREIGN KEY (`CODIGO`) REFERENCES `tb_producto` (`CODIGO`)
) ;

SELECT * FROM tb_factura1;

SELECT * FROM tb_vendedor;

SELECT * FROM tb_producto;

INSERT INTO tb_factura1
VALUES('0100', '2021-01-01', '1471156710', '256', 0.10 );
INSERT INTO tb_items_factura
VALUES('0100', '1002767', 100, 25),
('0100', '1004327', 200, 25),
('0100', '1013793', 300, 25);

DELIMITER //
CREATE TRIGGER TG_FACTURACION_DELETE
AFTER DELETE ON tb_items_factura
FOR EACH ROW BEGIN
  DELETE FROM tb_facturacion;
  INSERT INTO tb_facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM tb_factura1 A
  INNER JOIN
  tb_items_factura B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;
END //

DELIMITER //
CREATE TRIGGER TG_FACTURACION_UPDATE
AFTER UPDATE ON tb_items_factura
FOR EACH ROW BEGIN
  DELETE FROM tb_facturacion;
  INSERT INTO tb_facturacion
  SELECT A.FECHA, SUM(B.CANTIDAD * B.PRECIO) AS VENTA_TOTAL
  FROM tb_factura1 A
  INNER JOIN
  tb_items_factura B
  ON A.NUMERO = B.NUMERO
  GROUP BY A.FECHA;
END //

UPDATE tb_items_factura SET CANTIDAD = 800
WHERE NUMERO = '0101' AND CODIGO = '1002767';

DELETE FROM tb_items_factura
WHERE NUMERO = '0104' AND CODIGO = '1013793'; 
