-- CREANDO LA ESTRUCTURA DE LA BASE DE DATOS
CREATE DATABASE ventas_jugos;

CREATE SCHEMA IF NOT EXISTS ventas_jugos2 DEFAULT CHARSET utf32;

USE ventas_jugos;

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANO VARCHAR(50) NULL,
ENVASE VARCHAR(50) NULL,
PRECIO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
COMISION FLOAT NULL,
FECHA_ADMISION DATE NULL,
DE_VACACIONES BIT(1) NULL,
PRIMARY KEY(MATRICULA)
);

USE ventas_jugos;

CREATE TABLE tb_cliente(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NULL,
DIRECCION VARCHAR(100) NULL,
BARRIO VARCHAR(50) NULL,
CIUDAD VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CP VARCHAR(50) NULL,
FECHA_NAC DATE NULL,
EDAD INT(2) NULL,
SEXO VARCHAR(50) NULL,
LIMITE_CRED INT NULL,
VOLUMEN_COMP INT NULL,
PRIMERA_COMP BOOL NULL,
PRIMARY KEY (DNI)
);

SELECT * FROM tb_cliente;

CREATE TABLE tb_venta(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO)
);

ALTER TABLE tb_venta ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI);

ALTER TABLE tb_venta ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA);

SELECT * FROM tb_venta;

ALTER TABLE  tb_items_factura ADD CONSTRAINT FK_NUMERO
FOREIGN KEY (NUMERO) REFERENCES tb_venta(NUMERO);


ALTER TABLE tb_items_factura ADD CONSTRAINT FK_CODIGO
FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO);

SELECT * FROM tb_items_factura;

/* Lo que aprendimos en esta aula:

Aprendimos a crear una base de datos;
Aprendimos a crear una tabla;
La posibilidad de crear las tablas por un asistente;
Vimos cómo crear las relaciones entre las tablas;
Vimos que el nombre de la tabla también puede ser modificado tras su creación. */